language: java

services:
  - redis-server

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8    
    - stage: documentation
      name: "Publish documentation"
      if: (branch = master)
      script: chmod +x .travis/javadoc-push.sh && .travis/javadoc-push.sh

branches:
  only:
  - master
